/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.jmanderson.sonata.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.jmanderson.sonata.MPGBean;
import org.jmanderson.sonata.Processor;
import org.jmanderson.sonata.XMLBean;
import org.jmanderson.sonata.hibernate.Users;

/** 
 * MyEclipse Struts
 * Creation date: 10-28-2006
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/gaslist.jsp"
 */
public class ListAllGasAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		HttpSession session = request.getSession();
		
		Users user = (Users) session.getAttribute("user");
		if (user == null || !user.isValidated()) {
			return mapping.findForward("login");
		}
		
		XMLBean xmlBean = Processor.getAllEntries();
		MPGBean mpg = Processor.getMPGBean();
		
		session.setAttribute("xmlbean", xmlBean);
		
		if (mpg != null) {
			session.setAttribute("mpg", mpg);
		}
		else {
			session.removeAttribute("mpg");
		}
		
		return mapping.findForward("success");
	}
}
